### ISSUE TITLE
What is the recommended approach for handling identical Input object types and output object types ?

### ISSUE THREAD

**Issue by lorefnon** [indigotech/graphql-schema-decorator#15]
I have noticed that when decorating the same class with `@InputObjectType` and `@ObjectType` simultaneously, `Object.objectTypeFactory` throws (graphql-schema-decorator\lib\object_type_factory.js:20:15). 

```
@ObjectType()
@InputObjectType()
export class Bar {
    @Field()
    name: string;
}

@ObjectType()
@InputObjectType()
export class Foo extends BaseFoo {

    @Field()
    name: string;

    @List()
    @Field({type: Bar})
    bars: [Bar]
}

```

After that I attempted something like the following: 

```
export class BaseBar {
    @Field()
    name: string;
}

@ObjectType()
export class Bar extends BaseBar {}

@InputObjectType()
export class InputBar extends BaseBar{}

// Shared between input and output
export class BaseFoo {
    @Field()
    name: string;
} 

// Output type
@ObjectType()
export class Foo extends BaseFoo {
    @List()
    @Field({type: Bar})
    bars: [Bar]
}

// Input type
@InputObjectType()
export class InputFoo extends BaseFoo {
    @List()
    @Field({type: InputBar})
    bars: [InputBar]
}
```

However the above does not work and I get an error like below: 

```
Error: Foo.bars field type must be Output Type but got: [InputBar].
```

It gets resolved when I removed the shared base class and duplicated the shared properties:

```
// Output type
@ObjectType()
export class Foo extends BaseFoo {

    @Field()
    name: string;

    @List()
    @Field({type: Bar})
    bars: [Bar]
}

// Input type
@InputObjectType()
export class InputFoo extends BaseFoo {

    @Field()
    name: string;

    @List()
    @Field({type: InputBar})
    bars: [InputBar]
}
```

Is there a way to eliminate the redundancy here ?

**Comment by thiago-soliveira** [comment]
The structure we have today doesn't take that into account. In order to get this to work, some changes are required. But before addressing them, I'd like to discuss if these changes make sense or not.

Per GraphQL spec, Input Object and Object are different things. 

> Fields can define arguments that the client passes up with the query, to configure their behavior. These inputs can be Strings or Enums, but they sometimes need to be more complex than this.
&nbsp;  
The Object type... is inappropriate for re‐use here, because Objects can contain fields that express circular references or references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system.  
&nbsp;
An Input Object defines a set of input fields; the input fields are either scalars, enums, or other input objects. This allows arguments to accept arbitrarily complex structs.

So, I don't think using `@InputObjectType` and `@ObjectType` on the same class is a good approach for sharing code. Actually, I don't even know if sharing code between these types is a good thing.  
What if I wanted to add a `resolver` to my object type? Resolvers make no sense on an input object, then the `graphql-schema-decorator` would have to ignore them somehow.   

You see where this is going? Lots of complexity while trying to pursuit something that wasn't proposed by the GraphQL spec.

Well... Let's forget about all that for a moment. I do want to share some code between input and output objects. How we could do it?
Starting with the last approach you suggested, we have...

```typescript
export class BaseBar {
    @Field()
    name: string;
}
```

To me, it's just weird to see a non-decorated class using `@Field()` decorators. Maybe we should have a `@BaseObjectType` decorator. It would be responsible for holding information about base classes and it would be consulted by `@ObjectType` upon creation.

It could work.  What do you think? 

Considering the current structure we have, it might be a pain to make these changes.   
I really don't know if this change will bring real value to the library. I guess the only one way to find out is doing it.

**Comment by lorefnon** [comment]
Thanks for taking the time to reply. I am new to GraphQL and it is very likely that there exists a better approach that makes the need for this unnecessary. 

However my usecase is rather simple and am not able to understand how to accomplish this using graphql-schema-decorator without duplicating classes. 

Imagine I have a form which allows users to edit product details. When a user is editing the product details I fetch the existing details from the server and then the user edits the values through the form and submits the details back to the server. So in essence the data being fetched and the data being submitted must conceptually adhere to the same schema (Product details). So in this context, I am really having a hard time making sense of the separation between Input types and output types. 

Any feedback around addressing the above would be highly appreciated. 

I think the BaseObjectType decorator actually makes sense and I can try to put in some effort towards submitting a PR to make that happen. My familiarity with Typescript is in nascent stages as well, so it may take some time for me, but if we are optimistic about this direction, it would be a good learning exercise.

**Comment by felipesabino** [comment]
@lorefnon 

I guess a better approach would be to use GraphQL interfaces, but this is still pending to be implemented as a decorator as of #28.

But anyway, for a simple code reuse approach, your initial implementation should work if instead you used an `abstract` class for your `BaseBar` and `BaseFoo` classes, like the following

```
export abstract class BaseBar {
    @Field()
    name: string;
}

@ObjectType()
export class Bar extends BaseBar {}

@InputObjectType()
export class InputBar extends BaseBar{}

// Shared between input and output
export abstract class BaseFoo {
    @Field()
    name: string;
} 

// Output type
@ObjectType()
export class Foo extends BaseFoo {
    @List()
    @Field({type: Bar})
    bars: [Bar]
}

// Input type
@InputObjectType()
export class InputFoo extends BaseFoo {
    @List()
    @Field({type: InputBar})
    bars: [InputBar]
}
```

**Comment by felipesabino** [comment]
Hi @lorefnon, I will close this issue as it seems to be "solved". I will reopen it in case you need more help

**Comment by lorefnon** [comment]
@felipesabino Thanks for the solution here. I hadn't thought of using abstract classes.
