### ISSUE TITLE
this is undefined, @Root seems to be workaround

### ISSUE THREAD

**Issue by Bennit** [indigotech/graphql-schema-decorator#59]
Given the following setup:

Schema with RootQuery: { public: Public }
The Public ObjectType : { person(id: string): Person }
The Person ObjectType has a constructor (private data: PersonData) => data comes from a DB
The person ObjectType has a field { name(): string }

To access the data in the name() method I tried to use `this`, however this is undefined, even though the constructor is being properly executed. So I figured the data must be available via another way, indeed via the `@Root` annotation the actual instance of Person gets injected in the method's arguments.

Why do we need the `@Root` annotation? `this` is undefined in `@Field` methods, couldn't we simply point `this` to the correct value - as clearly it's available via `@Root` ?
Am I missing the point of what `@Root` does? I failed to find some docs on it other than the source.

Kind regards
Ben

**Comment by thiago-soliveira** [comment]
`@Root` gives you access to the `rootValue` available through the `graphql-js` . You can see some information about it here: https://github.com/graphql/graphql-js/issues/735

Regarding the problem you're facing while trying to access `this`. We have a very similar use case, where we have to access DB data on a `@Field` method, and we are able to access `this`. 

Maybe you could build an example where that happens, just so we could investigate and maybe find out what is happening.

**Comment by felipesabino** [comment]
Also, you `root` from the decorator is not specifically your  _Type_ object, you can send any value to be resolved and in this case, `this` would not be strongly typed and later access to `this`can become be very misleading and confusing.

**Comment by Bennit** [comment]
Hi guys, sorry it took so long but I kinda forgot about this issue.
With your comments I'm not convinced yet that "this" should not be available like what I describe.
Here is an example (npm i && npm start): https://github.com/Bennit/example-graphql-decorator

This is example output:

```json
{
    "errors": [
        {
            "message": "Cannot read property 'foo' of undefined",
            "locations": [{"line": 1,"column": 19}],
            "path": ["example","foo"]
        }
    ],
    "data": {
        "example": {
            "foo": null,
            "foo2": "bar",
            "thisProperties": "data [undefined] = undefined",
            "rootProperties": "data [object] = {\"foo\":\"bar\"}"
        }
    }
}
```

As you can see, the properties of this are only partially available, while root's properties are all there.
In another graphql decorator library I was able to use this directly and it helps a lot.
@felipesabino I don't get why you say "this" would not be strongly typed, as it is strongly typed in my example.

Concretely not having "this" makes me have to explicitly provide it through an argument of each field that accesses the data of the ObjectType instance.

Kind regards
Ben

**Comment by felipesabino** [comment]
@Bennit 

> I don't get why you say "this" would not be strongly typed, as it is strongly typed in my example.

Oh, ok, may be I needed to elaborate more, my bad. My point is that whatever is sent to be resolved is not necessary (actually almost never) an instance of the class being resolved.

Take the following implementation as an example

```
@ObjectType()
export class MyQueryClass {

  @Field({ type: MyReturnType})
  async MyQuery(): Promise<MyRandomClass> {
     return Promise.resolve(new MyRandomClass());
  }

  @Field({ type: MyReturnType})
  async AnotherQuery(): Promise<string> {
     return Promise.resolve('whatever');
  }

}

@ObjectType()
class MyReturnType {

  @Field({ type: GraphQLInt, nonNull: true})
  myReturnField(
    @Root() root: string | MyRandomClass, // using @Root() here allow for explicit strong typing
  ): number {
    // There are multiple types being used to resolve as MyReturnType
	// What type 'this' should be here? It can be both, but is not clear and could lead to confusion.
    if (typeof(root) === 'string') { return 1; }
    else if (root instanceof MyRandomClass) { return 2; }
    else { return 0; }
  }
}

// query could be sth like

query {
  MyQuery {
    myReturnField
  }
  AnotherQuery {
    myReturnField
  }
}
```


In this case, **if** `this` was set to have the value of `@Root()` it should be of type `string | MyRandomClass`, but it would not be clear for anyone reading the code.

Also, **if** `this` is not `undefined` as it is today, it should actually be of type `MyReturnType`, but that would allow accessing other properties/function of the class at any giving time, but the problem is that the resolving order is not determinant, so some times you could access a property and that could return the already-resolved value, which would be ok, but other times that property would be `undefined`, because it is still about to be resolved, which would make testing a huge nightmare.

Now, about your example at https://github.com/Bennit/example-graphql-decorator, you added a constructor to the graphql class 

```
@ObjectType()
export class ExampleType {

    constructor (private data: ExampleTypeData) {

    }
```

But that is indeed never called. Our library leverages `graphql-js` classes lifecycle management and AFAIK there no dependency injection-like feature that would handle your constructor to provide a `data` value to it. Instead `graphql-js` sends this information only on resolving time, calling the resolving function with several parameters and one of them it the `root` one, which would be your `data` value that we handle and provide access to via `@Root()`.

Anyway, I am in the dark on how to accomplish what you want without total control of classes lifecycle and also only having access to the _Root_ value on resolving time, but I am open to suggestions and ideas on how to achieve/implement it if you have some.

**Comment by Bennit** [comment]
OK I understand better now - thanks a lot for explaining. If I understand correctly it's actually about how the graphql library is being used. To be type safe I actually provided the 'MyRandomClass' instance as a property of MyReturnType, and *always* return exactly an instance of the type that I state in the graphql Field decorator. But indeed, there's nothing imposing this safety except for convention from the developer.

Perhaps we could use reflection to ensure the type of the Field annotation and the actual field's return type are the same. Probably you'll want to make this 'strict' mode optional to remain backwards compatible with people that do not want this type safety. When in strict mode you can inject this with the value of root. I've tried to find in the library code where 'this' is being proxied but did not immediately find it out. I'll try to get back to you on this with further ideas or a PR.

I personally enjoy much more to be able to use 'this' directly rather than having to specify (@Root() root: *Same type as this*) as an argument to each function that wants to access the data - however I will try to see if returning something else than what the actual return type is brings me any closer to achieving said ease of use.

Kind regards
Ben

**Comment by felipesabino** [comment]
@Bennit 

>  I've tried to find in the library code where 'this' is being proxied but did not immediately find it out

May be I can help with that. 

`@Root` injection as a function argument is [here](https://github.com/indigotech/graphql-schema-decorator/blob/ec42e6ab7543f89574cf952c8b2d673fa0436508/src/type-factory/field.type-factory.ts#L134-L139) and `this` as the resolving class instance is being applied [here](https://github.com/indigotech/graphql-schema-decorator/blob/ec42e6ab7543f89574cf952c8b2d673fa0436508/src/type-factory/field.type-factory.ts#L152) ant [here](https://github.com/indigotech/graphql-schema-decorator/blob/ec42e6ab7543f89574cf952c8b2d673fa0436508/src/type-factory/field.type-factory.ts#L157). A functional test for `@Root()` value is [here](https://github.com/indigotech/graphql-schema-decorator/blob/ec42e6ab7543f89574cf952c8b2d673fa0436508/src/specs/functional.spec.ts#L479).

Hopefully that can help you start experimenting 👍
