### ISSUE TITLE
Consider use-case: Using object also for different purpose

### ISSUE THREAD

**Issue by VojtaStanek** [indigotech/graphql-schema-decorator#63]
Hi,

I have a use-case which I was thinking about and I came across this library and I think I won't be so hard to alter it to suit this use-case.

I was thinking about having a class as an ORM entity definition (e.g. in [TypeORM](http://typeorm.io/#/entities/what-is-entity)), but it can be also easily used as a GraphQL types definition. 

But the when I add an `@ObjectType` decorator it is modified so it cannot be used as a pure class/object. This is how I aproximately would like it to work:
```ts
// exports the pure-class as it is (@Entity decorator does not modify it in any way)
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    @GQLField()
    id: number;

    @Column()
    @GQLField()
    firstName: string;

    @Column()
    @GQLField()
    lastName: string;

    @GQLField()
    get fullName(): string {
        return this.firstName + ' ' + this.lastName;
    }

    @Column()
    isActive: boolean;

}

// Maybe somewhere else:

@ObjectType({description: 'Get all users query.'})
export class UsersQuery {

  @Field({type: User /** this is the same User class as above */, pagination: true}) 
  async user(
    @Ctx() context: any, 
    @Arg({name: "id"}) id: number, 
  )  {
    // ORM fetches the data
    return await connection.getRepository(Person).findOneById(id);
  }
} 
```

Maybe it would be also great in this case also to expose a function that would generate the GQL ObjectType from the "pure" class if the user doesn't want to use your way of specifying resolve methods (e.g. explicitely specifing it as [here](https://github.com/sitepoint-editors/graphql-nodejs/blob/master/graphql/types/comment.js)).

What do you think about it? What do you think about modifing/extensing this lib to support it? 

Thanks a lot!

**Comment by felipesabino** [comment]
>  it is modified so it cannot be used as a pure class/object

What do you mean by that? I did not understand this statement.

Also, you are using `@Field({type: User /** this is the same User class as above */, pagination: true})`, which expects the resolve function (aka `async user(...)` function) to be of type `Promise<[User[], count]>` and you are returning the result of `.getRepository(Person). findOneById`, which  is just a `Person` object (or `Promise<Person>`. I know that the docs are still not clear about that (we are working on it at #23 ) but I believe you could have both decorators classes working together.

Can you create a repository with this example so that I can take a look and see what are the issues you are facing?

**Comment by VojtaStanek** [comment]
I closed it, because the thing was, that I thought that @ObjectType is modifing the target itself to be GraphQLObjectType, but it's not - it is only adding the info about it to metadata storage. Don't bother with this at all...
