### ISSUE TITLE
How to get query fields?

### ISSUE THREAD

**Issue by ryuuji3** [indigotech/graphql-schema-decorator#70]
For example, if my query is:
```gql
query {
 employees {
  firstName
  lastName
 }
}
```

The `EmployeeType` resolver is currently querying all fields and then only `firstName` and `lastName` is shown.

If I could get an array of fields requested, I could selectively query those fields to speed up queries. I didn't see a decorator to do this, however...

Maybe we could have a `@Fields` decorator for this purpose? Or is there an alternate way to do this already?

```ts
@ObjectType() 
export default class EmployeeQueries {
  @Field()
  async employees (@Fields() fields) {
    // return await employeesRepository.find()
    return await employeesRepository.find( select: fields )
  }
}
```

**Comment by felipesabino** [comment]
@ryuuji3 This is a very nice feature and unfortunately there is no way of doing that today.

I remember trying it once but got stuck on [`graphql-js`](https://github.com/graphql/graphql-js) API to retrieve this information for more complex queries. I remember having some issues parsing the query tree when the original query contained nested objects, interfaces, mutations or fragments, which at the time I found was too confusing to parse reliably.

I will leave this open so that we can tackle after [1.0](https://github.com/indigotech/graphql-schema-decorator/milestone/1) is released.

**Comment by ryuuji3** [comment]
Thanks for your reply @felipesabino 

If you couldn't figure it out, I'm not sure I'll be able to. But I'm going to play around and see if I can get something to work. 
Thanks again!

**Comment by ryuuji3** [comment]
I found a project I'm thinking of forking that could be used to achieve what you were looking for; https://github.com/robrichard/graphql-fields

Does this look promising to you?

**Comment by felipesabino** [comment]
> I found a project I'm thinking of forking that could be used to achieve what you were looking for; robrichard/graphql-fields
> Does this look promising to you?

Nice! It looks very promising indeed.

I believe you could even integrate it instead of copying/reimplementing from scratch and just call it  ([here?](https://github.com/indigotech/graphql-schema-decorator/blob/b24380399bfd366bc17dead883c7d6809176b564/src/type-factory/field.type-factory.ts#L127-L139)) whenever there is a `@Fields()` argument to be resolved.

**Comment by ryuuji3** [comment]
In the end, I think it's better to write a `@Info()` decorator. Which I had noticed you already planned to. Just to make sure I'm doing it right, 
1. Write new `@Info()` decorator in src/decorator
2. Add `class InfoArg extends Argument` to metadata/args, add interface to metadata/types
2. Update metadata-args storage, add info property and filter methods
3. Add builder method to metadata builder
4. And update the spots you showed in field type factory

Am I missing anything?

**Comment by felipesabino** [comment]
@ryuuji3 Nope, I guess you are on the right track 👍

**Comment by ryuuji3** [comment]
It's been quite a while. I apologize that I never got to it. I'll just close this issue.
